name: GSI request bot

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Kiểm Tra Trích Xuất
        uses: actions/checkout@master
        
      - name: Test
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git openjdk-8-jdk p7zip
          git clone --recurse-submodules https://github.com/penk2109/gsi_test bot
          cd bot
          dotnet run -c Release
      - name: Re-run Bot3 workflow
        continue-on-error: true
        timeout-minutes: 5
        run: |
          cd tmp/bot
          git commit --allow-empty -s -m "[LOOP] Re-run Bot3 workflow"
          git push -f
